/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticación de usuario interno
         * @description Punto de entrada a toda la aplicación: valida usuario y contraseña contra el catálogo interno de usuarios y, si son correctos, entrega el token que el resto de esta API exige en cada petición. Es el único endpoint que no requiere autenticación previa, por razones evidentes.
         */
        post: operations["iniciarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sucursales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar sucursales
         * @description Catálogo de referencia (puntos de venta y su formato) que alimenta los selectores de "sucursal destino" al crear una orden y de "sucursal" al dar de alta un usuario GERENTE_SUCURSAL. Cualquier usuario autenticado puede consultarlo: no expone información sensible y lo necesitan tanto pantallas de Compras como de Administración.
         */
        get: operations["listarSucursales"];
        put?: never;
        /**
         * Crear sucursal
         * @description Da de alta un punto de venta con su formato, que decide qué categorías de producto se le pueden pedir y si sus órdenes exigen cliente (Venta Directa). Reservado a ADMIN, como el resto de la administración de catálogos.
         */
        post: operations["crearSucursal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sucursales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar sucursal
         * @description Edita el nombre o el formato de una sucursal, o la activa/desactiva mediante el campo activo (una sucursal desactivada no puede elegirse como destino de órdenes nuevas; las órdenes que ya la tienen como destino siguen siendo editables). El formato no se puede cambiar una vez que la sucursal tiene órdenes: 409 con código formato_bloqueado. Para "cambiarlo" se desactiva la sucursal y se crea otra. Reservado a ADMIN.
         */
        put: operations["actualizarSucursal"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorías de producto
         * @description Catálogo de categorías de producto (herramientas, pinturas, etc.) que alimenta el selector de categoría al dar de alta o editar un producto. Cualquier usuario autenticado puede consultarlo: es información de referencia sin datos sensibles.
         */
        get: operations["listarCategorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar proveedores
         * @description Catálogo de proveedores disponibles para armar órdenes de compra y si están activos. Disponible para ADMIN y COMPRADOR (el comprador debe poder elegir proveedor al crear una orden). La clave de webhook solo se devuelve a ADMIN; para COMPRADOR el campo webhook_api_key viene nulo, porque quien la conoce puede registrar eventos en nombre del proveedor.
         */
        get: operations["listarProveedores"];
        put?: never;
        /**
         * Crear proveedor
         * @description Da de alta un nuevo proveedor en el catálogo y le genera automáticamente una clave de webhook para que pueda reportar eventos logísticos más adelante. Reservado a ADMIN, como el resto de la administración de catálogos: alta de proveedores es una decisión de negocio, no una operación del día a día de Compras.
         */
        post: operations["crearProveedor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar proveedor
         * @description Edita los datos de contacto de un proveedor existente, o lo activa/desactiva mediante el campo activo (un proveedor desactivado deja de estar disponible para nuevas órdenes). Reservado a ADMIN.
         */
        put: operations["actualizarProveedor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores/{id}/regenerar-clave-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Regenerar la clave de webhook del proveedor
         * @description Genera una clave de webhook nueva y devuelve el proveedor con ella. La clave anterior deja de autenticar de inmediato, asi que la nueva debe hacerse llegar al proveedor por un canal aparte. Sirve ante una fuga o para rotarla periodicamente. Reservado a ADMIN.
         */
        patch: operations["regenerarClaveWebhookProveedor"];
        trace?: never;
    };
    "/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar productos
         * @description Catálogo de productos que un COMPRADOR recorre para armar el detalle de una orden (con filtro opcional por categoría). Abierto también a ADMIN para las mismas pantallas de administración de catálogos.
         */
        get: operations["listarProductos"];
        put?: never;
        /**
         * Crear producto
         * @description Da de alta un nuevo producto en el catálogo, incluida la categoría que determina en qué formatos de sucursal se puede pedir. Reservado a ADMIN: un COMPRADOR elige productos existentes al armar una orden, no define el catálogo.
         */
        post: operations["crearProducto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar producto
         * @description Edita los datos de un producto existente (precio, unidades, categoría), o lo activa/desactiva mediante el campo activo. Reservado a ADMIN.
         */
        put: operations["actualizarProducto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar clientes
         * @description Catálogo de clientes finales, obligatorio para elegir uno al crear una orden con sucursal destino de Venta Directa. Abierto a COMPRADOR (quien arma esas órdenes) y a ADMIN (administración de catálogos).
         */
        get: operations["listarClientes"];
        put?: never;
        /**
         * Crear cliente
         * @description Da de alta un nuevo cliente final en el catálogo. Reservado a ADMIN, como el resto del mantenimiento de catálogos.
         */
        post: operations["crearCliente"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar cliente
         * @description Edita los datos de un cliente existente, o lo activa/desactiva mediante el campo activo. Reservado a ADMIN.
         */
        put: operations["actualizarCliente"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar usuarios
         * @description Cuenta con acceso al sistema (rol y, si aplica, sucursal asignada). Exclusivo de ADMIN: es gestión de identidades y permisos, fuera del alcance de cualquier otro rol.
         */
        get: operations["listarUsuarios"];
        put?: never;
        /**
         * Crear usuario
         * @description Da de alta una nueva cuenta de acceso, asignándole un rol y, si es GERENTE_SUCURSAL, la sucursal a la que queda restringida. Exclusivo de ADMIN.
         */
        post: operations["crearUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Actualizar usuario
         * @description Edita una cuenta existente (contraseña, rol, sucursal), o la activa/desactiva mediante el campo activo. Exclusivo de ADMIN.
         */
        put: operations["actualizarUsuario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar órdenes de compra
         * @description Vista central de trabajo de Compras: todas las órdenes visibles para el usuario autenticado, con filtros y paginación por cursor. Un GERENTE_SUCURSAL ve únicamente las órdenes de su propia sucursal (filtrado automático por el backend según su usuario, no por parámetro del cliente); ADMIN y COMPRADOR ven todas.
         */
        get: operations["listarOrdenes"];
        put?: never;
        /**
         * Crear orden de compra (estado inicial CREADA)
         * @description Punto de partida del flujo de Compras: registra una nueva orden con su detalle de productos, valida las reglas de negocio (formato de sucursal vs. categoría permitida, cliente obligatorio en Venta Directa) y calcula el total. Disponible para COMPRADOR, que es quien arma órdenes en el día a día, y ADMIN. Un GERENTE_SUCURSAL no crea órdenes: solo las recibe y las cierra.
         */
        post: operations["crearOrden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * Detalle de una orden de compra
         * @description Cabecera y detalle completos de una orden puntual. Mismo criterio de visibilidad que el listado: un GERENTE_SUCURSAL solo puede consultar órdenes de su propia sucursal.
         */
        get: operations["obtenerOrden"];
        /**
         * Modificar el detalle de una orden (solo si está en estado CREADA)
         * @description Corrige las líneas de una orden antes de que avance en su ciclo de vida; una vez aprobada, anulada o cerrada ya no se puede editar (ver respuesta 409). Mismos roles que pueden crear una orden: COMPRADOR y ADMIN.
         */
        put: operations["actualizarOrden"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transición CREADA → APROBADA (dispara notificación al proveedor)
         * @description Confirma la orden y dispara el correo de notificación al proveedor; solo es válida desde el estado CREADA (ver respuesta 409). La ejecuta quien la creó en primer lugar: COMPRADOR o ADMIN.
         */
        patch: operations["aprobarOrden"];
        trace?: never;
    };
    "/ordenes/{id}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transición a ANULADA (requiere motivo; no permitida desde CERRADA)
         * @description Cancela una orden que ya no se necesita, dejando registrado el motivo para auditoría. No es una acción destructiva a nivel de datos (la orden queda anulada, no se borra) y no se puede aplicar sobre una orden ya CERRADA. Misma autorización que crearla y aprobarla: COMPRADOR o ADMIN.
         */
        patch: operations["anularOrden"];
        trace?: never;
    };
    "/ordenes/{id}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transición APROBADA → CERRADA (confirma recepción)
         * @description Cierra el ciclo de vida de la orden confirmando si la mercancía llegó conforme o no. Solo válida desde APROBADA (ver respuesta 409). La ejecuta quien recibe físicamente el pedido: el GERENTE_SUCURSAL de la sucursal destino de la orden (nunca de otra), o ADMIN. Un COMPRADOR no puede cerrarla — no es quien recibe la mercancía.
         */
        patch: operations["cerrarOrden"];
        trace?: never;
    };
    "/ordenes/{id}/linea-tiempo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * Historial combinado (auditoría interna + eventos de proveedor), ordenado por fecha
         * @description Vista de seguimiento pensada para que quien sigue una orden entienda su ciclo de vida completo de un vistazo, sin cruzar dos endpoints distintos: combina los cambios de estado internos con los eventos logísticos que reporta el proveedor. Mismos roles y misma restricción de sucursal para GERENTE_SUCURSAL que ver el detalle de la orden.
         */
        get: operations["obtenerLineaTiempoOrden"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auditoria/ordenes/{numeroOrden}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description El numero_orden visible en toda la aplicacion (ej. OC-2026-000123), no el id interno de base de datos - es el unico identificador de la orden que un ADMIN conoce de memoria. */
                numeroOrden: string;
            };
            cookie?: never;
        };
        /**
         * Historial de transiciones de estado de una orden (solo auditoría interna)
         * @description Bitácora cruda de quién cambió el estado de la orden y cuándo, sin mezclar eventos del proveedor (para eso está la línea de tiempo combinada). Es una herramienta de supervisión/control, no de seguimiento operativo del día a día: exclusiva de ADMIN.
         */
        get: operations["obtenerAuditoriaOrden"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/importaciones/plantilla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar plantilla Excel para carga masiva de órdenes
         * @description Punto de partida para una carga masiva: un .xlsx de ejemplo con la hoja "Ordenes" (columnas exactas que espera el endpoint de importación) más hojas de referencia (Proveedores/Sucursales/ Clientes/Productos) con listas desplegables, para que el usuario elija un nombre válido en vez de tener que conocer un ID interno. Mismos roles que pueden crear órdenes de forma individual, ya que la carga masiva reutiliza exactamente el mismo servicio y las mismas reglas de negocio.
         */
        get: operations["descargarPlantillaImportacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/importaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Carga masiva de órdenes de compra vía Excel
         * @description Registra varias órdenes de una sola vez para casos de reposición periódica, pedidos recurrentes o migración de datos: agrupa las filas de la hoja "Ordenes" del archivo .xlsx por referencia_lote, resuelve proveedor/sucursal/cliente por nombre y producto por código, arma el mismo OrdenCompraRequest que el flujo individual y reutiliza el mismo servicio de creación de orden, así que ninguna regla de negocio se duplica ni se relaja. Atomicidad por orden (lote), no por archivo completo: un lote inválido se rechaza sin afectar a los demás. Mismos roles que crear una orden individual.
         */
        post: operations["importarOrdenes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/{id}/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        /**
         * Exportar una orden de compra como PDF
         * @description Genera el documento formal de la orden (cabecera + detalle) para enviar al proveedor, imprimir o archivar. Mismo control de acceso que consultar la orden: GERENTE_SUCURSAL restringido a su propia sucursal.
         */
        get: operations["exportarOrdenPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ordenes/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar un reporte Excel de órdenes de compra
         * @description Reporte tabular para análisis o conciliación externa, con los mismos filtros que el listado. Una fila por línea de producto (no por orden), con los datos de cabecera repetidos en cada fila, para no perder el detalle de qué se compró. Mismos roles y misma restricción de sucursal para GERENTE_SUCURSAL que el listado de órdenes.
         */
        get: operations["exportarOrdenesExcel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un evento logístico reportado por el proveedor
         * @description Punto de integración para que el sistema del proveedor informe el avance de una orden (aceptada, despachada, entregada, etc.), sin depender de que un usuario interno la actualice a mano. Puramente informativo: ningún tipo de evento (incluido ENTREGADA o RECHAZADA) dispara una transición de estado interna de la orden. No usa el JWT del resto de la API: se autentica con la clave propia del proveedor.
         */
        post: operations["registrarEventoProveedor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Rol: "ADMIN" | "COMPRADOR" | "GERENTE_SUCURSAL";
        /** @enum {string} */
        FormatoSucursal: "FERRETERIA" | "FERRETERIA_CONSTRUCCION" | "VENTA_DIRECTA";
        /** @enum {string} */
        EstadoOrden: "CREADA" | "APROBADA" | "ANULADA" | "CERRADA";
        /** @enum {string} */
        TipoEventoProveedor: "ACEPTADA" | "RECHAZADA" | "PREPARADA" | "DESPACHADA" | "ENTREGADA";
        ErrorResponse: {
            error?: {
                /** @enum {string} */
                type: "invalid_request_error" | "authentication_error" | "state_conflict_error" | "api_error";
                /** @example categoria_no_permitida */
                code: string;
                message: string;
                param?: string | null;
            };
        };
        ListEnvelope: {
            /** @enum {string} */
            object?: "list";
            has_more?: boolean;
        };
        Sucursal: {
            /** @enum {string} */
            object?: "sucursal";
            id?: number;
            nombre?: string;
            formato?: components["schemas"]["FormatoSucursal"];
            activo?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Categoria: {
            /** @enum {string} */
            object?: "categoria";
            id?: number;
            nombre?: string;
        };
        Proveedor: {
            /** @enum {string} */
            object?: "proveedor";
            id?: number;
            nombre?: string;
            /** Format: email */
            email?: string;
            telefono?: string | null;
            direccion?: string | null;
            /** @description Generada automaticamente al crear el proveedor. Se entrega al proveedor real fuera de banda. ADMIN puede consultarla via GET y rotarla con PATCH /proveedores/{id}/regenerar-clave-webhook. */
            webhook_api_key?: string | null;
            /**
             * Format: double
             * @description Descuento maximo (en porcentaje) que se puede negociar sobre el precio de catalogo de cualquier producto de este proveedor. 0 junto con aumento_maximo_pct = 0 significa que no se negocia (se compra al precio de catalogo).
             */
            descuento_maximo_pct?: number;
            /**
             * Format: double
             * @description Aumento maximo (en porcentaje) que se acepta sobre el precio de catalogo.
             */
            aumento_maximo_pct?: number;
            activo?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProveedorRequest: {
            nombre: string;
            /** Format: email */
            email: string;
            telefono?: string;
            direccion?: string;
            /** @description Omitido en creacion equivale a true; omitido en edicion preserva el valor actual. */
            activo?: boolean;
            /**
             * Format: double
             * @description Porcentaje maximo de descuento negociable. Omitido en creacion equivale a 0; omitido en edicion preserva el valor actual. Maximo dos decimales.
             */
            descuento_maximo_pct?: number;
            /**
             * Format: double
             * @description Porcentaje maximo de aumento aceptable. Omitido en creacion equivale a 0; omitido en edicion preserva el valor actual. Maximo dos decimales.
             */
            aumento_maximo_pct?: number;
        };
        SucursalRequest: {
            nombre: string;
            formato: components["schemas"]["FormatoSucursal"];
            /** @description Omitido en creacion equivale a true; omitido en edicion preserva el valor actual. */
            activo?: boolean;
        };
        Producto: {
            /** @enum {string} */
            object?: "producto";
            id?: number;
            codigo?: string;
            nombre?: string;
            categoria_id?: number;
            /** Format: double */
            precio?: number;
            unidad_venta?: string;
            unidad_compra?: string;
            /** Format: double */
            factor_conversion?: number;
            activo?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProductoRequest: {
            codigo: string;
            nombre: string;
            categoria_id: number;
            /** Format: double */
            precio: number;
            unidad_venta: string;
            unidad_compra: string;
            /**
             * Format: double
             * @default 1
             */
            factor_conversion: number;
            /** @description Omitido en creacion equivale a true; omitido en edicion preserva el valor actual. */
            activo?: boolean;
        };
        Cliente: {
            /** @enum {string} */
            object?: "cliente";
            id?: number;
            nombre?: string;
            /** @enum {string} */
            tipo?: "INDUSTRIAL" | "CONTRATISTA" | "COMERCIO";
            /** Format: email */
            email?: string | null;
            activo?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ClienteRequest: {
            nombre: string;
            /** @enum {string} */
            tipo: "INDUSTRIAL" | "CONTRATISTA" | "COMERCIO";
            /** Format: email */
            email?: string;
            /** @description Omitido en creacion equivale a true; omitido en edicion preserva el valor actual. */
            activo?: boolean;
        };
        Usuario: {
            /** @enum {string} */
            object?: "usuario";
            id?: number;
            username?: string;
            rol?: components["schemas"]["Rol"];
            sucursal_id?: number | null;
            activo?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        UsuarioRequest: {
            username: string;
            /**
             * Format: password
             * @description Obligatorio al crear; en edicion, si se omite se conserva la contraseña actual.
             */
            password?: string;
            rol: components["schemas"]["Rol"];
            /** @description Obligatorio si rol = GERENTE_SUCURSAL */
            sucursal_id?: number | null;
            /** @description Omitido en creacion equivale a true; omitido en edicion preserva el valor actual. */
            activo?: boolean;
        };
        DetalleRequest: {
            producto_id: number;
            /** Format: double */
            cantidad: number;
            /**
             * Format: double
             * @description Precio unitario negociado (maximo dos decimales). Opcional: omitido, la linea usa el precio de catalogo (o, al editar una orden, el que la linea ya tenia). Debe estar entre catalogo x (1 - descuento_maximo_pct) y catalogo x (1 + aumento_maximo_pct) del proveedor de la orden, ambos extremos incluidos; el catalogo de referencia es el guardado en la linea (precio_catalogo), no el vigente hoy. Fuera de rango responde 400 con codigo precio_fuera_de_rango.
             */
            precio_unitario?: number;
        };
        OrdenCompraDetalle: {
            /** @enum {string} */
            object?: "orden_compra_detalle";
            id?: number;
            producto_id?: number;
            producto_codigo?: string;
            producto_nombre?: string;
            /** Format: double */
            cantidad?: number;
            /** Format: double */
            precio_unitario?: number;
            /**
             * Format: double
             * @description Precio de catalogo vigente al crear la linea. Si difiere de precio_unitario, la linea se negocio.
             */
            precio_catalogo?: number;
            /** Format: double */
            subtotal?: number;
        };
        OrdenCompraRequest: {
            proveedor_id: number;
            sucursal_destino_id: number;
            /** @description Obligatorio si la sucursal destino tiene formato VENTA_DIRECTA */
            cliente_id?: number | null;
            /** Format: date */
            fecha_necesaria: string;
            detalle: components["schemas"]["DetalleRequest"][];
        };
        OrdenCompra: {
            /** @enum {string} */
            object?: "orden_compra";
            id?: number;
            /** @example OC-2026-000123 */
            numero_orden?: string;
            estado?: components["schemas"]["EstadoOrden"];
            proveedor_id?: number;
            sucursal_destino_id?: number;
            cliente_id?: number | null;
            cliente_nombre?: string | null;
            /** Format: date */
            fecha_necesaria?: string;
            /** Format: double */
            total?: number;
            motivo_anulacion?: string | null;
            conforme?: boolean | null;
            observacion_cierre?: string | null;
            detalle?: components["schemas"]["OrdenCompraDetalle"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** @description Presente solo si la request incluyo ?expand=proveedor; ausente en caso contrario. */
            proveedor?: components["schemas"]["Proveedor"] | null;
        };
        AuditoriaEvento: {
            /** @enum {string} */
            object?: "auditoria_evento";
            id?: number;
            orden_compra_id?: number;
            estado_anterior?: components["schemas"]["EstadoOrden"];
            estado_nuevo?: components["schemas"]["EstadoOrden"];
            usuario_id?: number;
            observacion?: string | null;
            /** Format: date-time */
            fecha?: string;
        };
        EventoProveedor: {
            /** @enum {string} */
            object?: "evento_proveedor";
            id?: number;
            orden_compra_id?: number;
            tipo_evento?: components["schemas"]["TipoEventoProveedor"];
            observacion?: string | null;
            /** Format: date-time */
            fecha_evento?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Elemento combinado de auditoría interna o evento de proveedor, discriminado por "origen" */
        LineaTiempoItem: {
            /** @enum {string} */
            origen?: "interno" | "proveedor";
            /** @description estado_nuevo si origen=interno, tipo_evento si origen=proveedor */
            tipo?: string;
            observacion?: string | null;
            /** Format: date-time */
            fecha?: string;
        };
        ImportacionLoteResponse: {
            /** @enum {string} */
            object?: "importacion_lote";
            ordenes_creadas?: {
                referencia_lote?: string;
                orden_id?: number;
                /** @example OC-2026-000145 */
                numero_orden?: string;
            }[];
            ordenes_rechazadas?: {
                referencia_lote?: string;
                error?: {
                    type?: string;
                    code?: string;
                    message?: string;
                    param?: string | null;
                };
            }[];
        };
    };
    responses: {
        /** @description Error de validación de entrada */
        InvalidRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Credenciales inválidas o token ausente/expirado */
        AuthenticationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso no encontrado */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Transición de estado inválida para el estado actual de la orden */
        StateConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdPathParam: number;
        /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
        IdempotencyKey: string;
        Limit: number;
        /** @description Cursor de paginación (número de orden del último elemento visto) */
        StartingAfter: string;
        /** @description Relaciones a embeber en la respuesta, ej. ?expand=proveedor&expand=linea_tiempo */
        Expand: string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Autenticación exitosa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        object?: "login_response";
                        access_token?: string;
                        /** @enum {string} */
                        token_type?: "Bearer";
                        /** @description segundos hasta expiración */
                        expires_in?: number;
                        rol?: components["schemas"]["Rol"];
                    };
                };
            };
            401: components["responses"]["AuthenticationError"];
        };
    };
    listarSucursales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de sucursales */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Sucursal"][];
                    };
                };
            };
        };
    };
    crearSucursal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SucursalRequest"];
            };
        };
        responses: {
            /** @description Sucursal creada */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sucursal"];
                };
            };
            400: components["responses"]["InvalidRequestError"];
            /** @description El usuario no es ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    actualizarSucursal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SucursalRequest"];
            };
        };
        responses: {
            /** @description Sucursal actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sucursal"];
                };
            };
            400: components["responses"]["InvalidRequestError"];
            /** @description El usuario no es ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            /** @description El formato no se puede cambiar porque la sucursal ya tiene órdenes (código formato_bloqueado) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listarCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de categorías */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Categoria"][];
                    };
                };
            };
        };
    };
    listarProveedores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de proveedores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Proveedor"][];
                    };
                };
            };
        };
    };
    crearProveedor: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorRequest"];
            };
        };
        responses: {
            /** @description Proveedor creado */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            400: components["responses"]["InvalidRequestError"];
        };
    };
    actualizarProveedor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProveedorRequest"];
            };
        };
        responses: {
            /** @description Proveedor actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    regenerarClaveWebhookProveedor: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clave regenerada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            /** @description El usuario no es ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    listarProductos: {
        parameters: {
            query?: {
                /** @description Filtrar por categoría */
                categoria_id?: number;
                /** @description Devuelve solo los productos cuya categoría está permitida para el formato de esa sucursal, es decir, los que se pueden pedir para ella. */
                sucursal_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de productos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Producto"][];
                    };
                };
            };
        };
    };
    crearProducto: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoRequest"];
            };
        };
        responses: {
            /** @description Producto creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Producto"];
                };
            };
        };
    };
    actualizarProducto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoRequest"];
            };
        };
        responses: {
            /** @description Producto actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Producto"];
                };
            };
        };
    };
    listarClientes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Cliente"][];
                    };
                };
            };
        };
    };
    crearCliente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteRequest"];
            };
        };
        responses: {
            /** @description Cliente creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"];
                };
            };
        };
    };
    actualizarCliente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteRequest"];
            };
        };
        responses: {
            /** @description Cliente actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"];
                };
            };
        };
    };
    listarUsuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de usuarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["Usuario"][];
                    };
                };
            };
        };
    };
    crearUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
        };
    };
    actualizarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
        };
    };
    listarOrdenes: {
        parameters: {
            query?: {
                estado?: components["schemas"]["EstadoOrden"];
                proveedor_id?: number;
                sucursal_id?: number;
                cliente_id?: number;
                /** @description Busca coincidencia parcial, sin distinguir mayúsculas/minúsculas (ej. "123" encuentra "OC-2026-000123"). */
                numero_orden?: string;
                /** @description Filtra por fecha_necesaria >= este valor. Se puede usar sola o junto a fecha_hasta. */
                fecha_desde?: string;
                /** @description Filtra por fecha_necesaria <= este valor. Se puede usar sola o junto a fecha_desde. */
                fecha_hasta?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Cursor de paginación (número de orden del último elemento visto) */
                starting_after?: components["parameters"]["StartingAfter"];
                /** @description Relaciones a embeber en la respuesta, ej. ?expand=proveedor&expand=linea_tiempo */
                expand?: components["parameters"]["Expand"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado de órdenes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["OrdenCompra"][];
                    };
                };
            };
            /** @description fecha_desde posterior a fecha_hasta */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    crearOrden: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdenCompraRequest"];
            };
        };
        responses: {
            /** @description Orden creada */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            400: components["responses"]["InvalidRequestError"];
        };
    };
    obtenerOrden: {
        parameters: {
            query?: {
                /** @description Relaciones a embeber en la respuesta, ej. ?expand=proveedor&expand=linea_tiempo */
                expand?: components["parameters"]["Expand"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de la orden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            /** @description GERENTE_SUCURSAL intentando acceder a una orden de otra sucursal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    actualizarOrden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdenCompraRequest"];
            };
        };
        responses: {
            /** @description Orden actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            409: components["responses"]["StateConflictError"];
        };
    };
    aprobarOrden: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orden aprobada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            409: components["responses"]["StateConflictError"];
        };
    };
    anularOrden: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    motivo: string;
                };
            };
        };
        responses: {
            /** @description Orden anulada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            409: components["responses"]["StateConflictError"];
        };
    };
    cerrarOrden: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    conforme: boolean;
                    observacion?: string;
                };
            };
        };
        responses: {
            /** @description Orden cerrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdenCompra"];
                };
            };
            /** @description Un COMPRADOR, o un GERENTE_SUCURSAL de otra sucursal, no puede ejecutar esta transición */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: components["responses"]["StateConflictError"];
        };
    };
    obtenerLineaTiempoOrden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Línea de tiempo de la orden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["LineaTiempoItem"][];
                    };
                };
            };
        };
    };
    obtenerAuditoriaOrden: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description El numero_orden visible en toda la aplicacion (ej. OC-2026-000123), no el id interno de base de datos - es el unico identificador de la orden que un ADMIN conoce de memoria. */
                numeroOrden: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bitácora de auditoría */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope"] & {
                        data?: components["schemas"]["AuditoriaEvento"][];
                    };
                };
            };
        };
    };
    descargarPlantillaImportacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo .xlsx de plantilla */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    importarOrdenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    archivo: string;
                };
            };
        };
        responses: {
            /** @description Reporte de resultado de la importación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportacionLoteResponse"];
                };
            };
        };
    };
    exportarOrdenPdf: {
        parameters: {
            query: {
                formato: "pdf";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documento PDF de la orden (cabecera + detalle) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description GERENTE_SUCURSAL intentando exportar una orden de otra sucursal */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportarOrdenesExcel: {
        parameters: {
            query: {
                formato: "xlsx";
                estado?: components["schemas"]["EstadoOrden"];
                proveedor_id?: number;
                sucursal_id?: number;
                cliente_id?: number;
                numero_orden?: string;
                fecha_desde?: string;
                fecha_hasta?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reporte .xlsx */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            /** @description fecha_desde posterior a fecha_hasta */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registrarEventoProveedor: {
        parameters: {
            query?: never;
            header?: {
                /** @description Clave generada por el cliente para evitar reprocesar la misma operación ante reintentos */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    numero_orden: string;
                    tipo_evento: components["schemas"]["TipoEventoProveedor"];
                    observacion?: string;
                    /** Format: date-time */
                    fecha_evento: string;
                };
            };
        };
        responses: {
            /** @description Evento registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoProveedor"];
                };
            };
            /** @description API key ausente o inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
